import 'package:flutter/material.dart';

import '../data/models/account_model.dart';
import '../data/models/category_model.dart';
import '../data/models/ledger_model.dart';
import '../data/models/transaction_model.dart';

class AppData {
  static List<LedgerModel> ledgers = [
    LedgerModel.withId(id: 0, name: "Student ledger", budget: 0.0),
    LedgerModel.withId(id: 1, name: "Home ledger", budget: 0.0),
  ];

  static List<AccountModel> accounts = [
    AccountModel.withId(
      id: 0,
      name: "Cash",
      iconCodePoint: Icons.money_sharp.codePoint,
      iconFamily: "MaterialIcons",
    ),
    AccountModel.withId(
      id: 1,
      name: "Credit card",
      iconCodePoint: Icons.credit_card.codePoint,
      iconFamily: "MaterialIcons",
    ),
    AccountModel.withId(
      id: 2,
      name: "Debit card",
      iconCodePoint: Icons.credit_card.codePoint,
      iconFamily: "MaterialIcons",
    ),
  ];

  static List<CategoryModel> categories = [
    CategoryModel.withId(
      id: 3,
      name: "Salary",
      iconCodePoint: Icons.money_outlined.codePoint,
      iconFamily: "MaterialIcons",
      transactionType: TransactionType.INCOME,
    ),
    CategoryModel.withId(
      id: 4,
      name: "Food",
      iconCodePoint: Icons.fastfood_outlined.codePoint,
      iconFamily: "MaterialIcons",
      transactionType: TransactionType.EXPENSE,
    ),
    CategoryModel.withId(
      id: 5,
      name: "Game",
      iconCodePoint: Icons.gamepad_outlined.codePoint,
      iconFamily: "MaterialIcons",
      transactionType: TransactionType.EXPENSE,
    ),
    CategoryModel.withId(
      id: 6,
      name: "Internet",
      iconCodePoint: Icons.wifi.codePoint,
      iconFamily: "MaterialIcons",
      transactionType: TransactionType.EXPENSE,
    ),
    CategoryModel.withId(
      id: 7,
      name: "Mobile",
      iconCodePoint: Icons.mobile_friendly.codePoint,
      iconFamily: "MaterialIcons",
      transactionType: TransactionType.EXPENSE,
    ),
    CategoryModel.withId(
      id: 8,
      name: "Electronic",
      iconCodePoint: Icons.camera_alt_outlined.codePoint,
      iconFamily: "MaterialIcons",
      transactionType: TransactionType.EXPENSE,
    ),
    CategoryModel.withId(
      id: 9,
      name: "Book",
      iconCodePoint: Icons.book_outlined.codePoint,
      iconFamily: "MaterialIcons",
      transactionType: TransactionType.EXPENSE,
    ),
  ];

  static CategoryModel transferCategory = CategoryModel.withId(
    id: 0,
    name: "Transfer",
    transactionType: TransactionType.TRANSFER,
    iconCodePoint: Icons.sync_alt.codePoint,
    iconFamily: "MaterialIcons",
  );

  // static CategoryModel defaultExpenseCategory = CategoryModel.withId(
  //   id: 1,
  //   name: "expense",
  //   transactionType: TransactionType.EXPENSE,
  //   iconCodePoint: Icons.book_outlined.codePoint,
  //   iconFamily: "MaterialIcons",
  // );

  // static CategoryModel defaultIncomeCategory = CategoryModel.withId(
  //   id: 2,
  //   name: "income",
  //   transactionType: TransactionType.INCOME,
  //   iconCodePoint: Icons.book_outlined.codePoint,
  //   iconFamily: "MaterialIcons",
  // );

  static List<TransactionModel> transactions = [
    // TransactionModel(
    //   amount: 100.0,
    //   date: DateTime(2021, 1, 1),
    //   categoryId: categories[0].id,
    //   category: categories[0],
    //   accountId: accounts[0].id,
    //   account: accounts[0],
    //   ledgerId: ledgers[0].id,
    //   ledger: ledgers[0],
    // ),
    // TransactionModel(
    //   amount: 450.0,
    //   date: DateTime(2021, 1, 1),
    //   categoryId: categories[2].id,
    //   category: categories[2],
    //   accountId: accounts[0].id,
    //   account: accounts[0],
    //   ledgerId: ledgers[0].id,
    //   ledger: ledgers[0],
    // ),
    // TransactionModel(
    //   amount: 400.0,
    //   date: DateTime(2021, 1, 5),
    //   categoryId: categories[3].id,
    //   category: categories[3],
    //   accountId: accounts[0].id,
    //   account: accounts[0],
    //   ledgerId: ledgers[0].id,
    //   ledger: ledgers[0],
    // ),
    // TransactionModel(
    //   amount: 56400.0,
    //   date: DateTime(2021, 1, 2),
    //   categoryId: categories[4].id,
    //   category: categories[4],
    //   accountId: accounts[0].id,
    //   account: accounts[0],
    //   ledgerId: ledgers[0].id,
    //   ledger: ledgers[0],
    // ),
    // TransactionModel(
    //   amount: 4600.0,
    //   date: DateTime(2021, 2, 1),
    //   categoryId: categories[1].id,
    //   category: categories[1],
    //   accountId: accounts[0].id,
    //   account: accounts[0],
    //   ledgerId: ledgers[0].id,
    //   ledger: ledgers[0],
    // ),
    // TransactionModel(
    //   amount: 100.0,
    //   date: DateTime(2021, 2, 12),
    //   categoryId: categories[2].id,
    //   category: categories[2],
    //   accountId: accounts[0].id,
    //   account: accounts[0],
    //   ledgerId: ledgers[0].id,
    //   ledger: ledgers[0],
    // ),
    // TransactionModel(
    //   amount: 100.0,
    //   date: DateTime(2021, 2, 14),
    //   categoryId: categories[3].id,
    //   category: categories[3],
    //   accountId: accounts[0].id,
    //   account: accounts[0],
    //   ledgerId: ledgers[0].id,
    //   ledger: ledgers[0],
    // ),
  ];

  static List<Icon> iconList = [
    Icon(Icons.credit_card),
    Icon(Icons.monetization_on),
    Icon(Icons.money),
    Icon(Icons.book_outlined),
    Icon(Icons.card_giftcard_outlined),
    Icon(Icons.card_travel_outlined),
    Icon(Icons.commute_outlined),
    Icon(Icons.event_seat_outlined),
    Icon(Icons.eco_outlined),
    Icon(Icons.face_outlined),
    Icon(Icons.flight_outlined),
    Icon(Icons.pets_outlined),
    Icon(Icons.settings_input_hdmi_outlined),
    Icon(Icons.shopping_bag_outlined),
    Icon(Icons.shopping_basket_outlined),
    Icon(Icons.shopping_cart_outlined),
    Icon(Icons.store_outlined),
    Icon(Icons.movie_outlined),
    Icon(Icons.phone_outlined),
    Icon(Icons.phone_android_outlined),
    Icon(Icons.weekend_outlined),
    Icon(Icons.devices_outlined),
    Icon(Icons.computer_outlined),
    Icon(Icons.desktop_mac_outlined),
    Icon(Icons.devices_other_outlined),
    Icon(Icons.headset_mic_outlined),
    Icon(Icons.headset_mic_outlined),
    Icon(Icons.laptop_windows_outlined),
    Icon(Icons.memory_outlined),
    Icon(Icons.speaker_outlined),
    Icon(Icons.toys_outlined),
    Icon(Icons.videogame_asset_outlined),
    Icon(Icons.agriculture_outlined),
    Icon(Icons.cleaning_services_outlined),
    Icon(Icons.directions_bike_outlined),
    Icon(Icons.directions_boat_outlined),
    Icon(Icons.directions_bus_outlined),
    Icon(Icons.directions_car_outlined),
    Icon(Icons.directions_railway_outlined),
    Icon(Icons.directions_run_outlined),
    Icon(Icons.electrical_services_outlined),
    Icon(Icons.ev_station_outlined),
    Icon(Icons.handyman_outlined),
    Icon(Icons.fastfood),
    Icon(Icons.hotel),
    Icon(Icons.local_bar),
    Icon(Icons.local_cafe),
    Icon(Icons.local_dining),
    Icon(Icons.local_gas_station),
    Icon(Icons.local_laundry_service_outlined),
    Icon(Icons.local_movies_outlined),
    Icon(Icons.local_parking),
    Icon(Icons.local_pizza),
    Icon(Icons.local_taxi_outlined),
    Icon(Icons.local_shipping_outlined),
    Icon(Icons.restaurant_outlined),
    Icon(Icons.payments),
    Icon(Icons.beach_access_outlined),
    Icon(Icons.casino_outlined),
    Icon(Icons.child_care_outlined),
    Icon(Icons.fitness_center_outlined),
    Icon(Icons.house_outlined),
    Icon(Icons.pool_outlined),
    Icon(Icons.smoking_rooms_outlined),
    Icon(Icons.cake),
    Icon(Icons.elderly_outlined),
    Icon(Icons.masks),
    Icon(Icons.lunch_dining),
    Icon(Icons.school),
    Icon(Icons.science),
    Icon(Icons.self_improvement_outlined),
  ];
}
